name = "costinghub-app"
compatibility_date = "2026-06-14"

[build]
command = "npm run build"
cwd = "./"

[assets]
directory = "./dist"

[env.production]
name = "costinghub-app-production"

[env.production.vars]
ENVIRONMENT = "production"

