name = "costinghub-app"
type = "javascript"
account_id = ""
workers_dev = true

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[[env.production]]
name = "costinghub-app-production"

[env.production.vars]
ENVIRONMENT = "production"

[build.upload]
format = "service-worker"

