CREATE TABLE IF NOT EXISTS stamping_results (
    id TEXT PRIMARY KEY,
    calculation_id UUID REFERENCES calculations(id) ON DELETE CASCADE,
    gross_weight_kg NUMERIC,
    scrap_weight_kg NUMERIC,
    material_cost_raw NUMERIC,
    recovered_scrap_value NUMERIC,
    net_material_cost NUMERIC,
    tooling_amortization_per_part NUMERIC,
    setup_cost_per_part NUMERIC,
    shearing_cost_per_part NUMERIC,
    forming_cost_per_part NUMERIC,
    laser_cost_per_part NUMERIC,
    bending_cost_per_part NUMERIC,
    secondary_cost_per_part NUMERIC,
    inspection_cost_per_part NUMERIC,
    total_manufacturing_cost NUMERIC,
    base_unit_cost NUMERIC,
    sga_amount NUMERIC,
    profit_amount NUMERIC,
    logistics_amount NUMERIC,
    final_unit_cost NUMERIC,
    annual_spend NUMERIC,
    process_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
