
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ShieldCheck, Loader2 } from 'lucide-react';
import { AuthService } from '../services/supabaseService';
import { UserRole } from '../types';

export const MFA: React.FC = () => {
  const navigate = useNavigate();
  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    if (code.length < 6) return;

    setLoading(true);
    setError('');
    
    try {
      const isValid = await AuthService.verifyMFA(code);
      
      if (isValid) {
        const user = AuthService.getCurrentUser();
        if (user?.role === UserRole.SUPER_ADMIN) {
          navigate('/super-admin');
        } else {
          navigate('/dashboard');
        }
      } else {
        setError('Verification failed. The code may be expired or incorrect.');
      }
    } catch (err: any) {
      setError(err.message || 'An error occurred during verification.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-slate-900 flex items-center justify-center p-4 relative">
      <div className="absolute top-6 left-6 flex items-center gap-2">
        <div className="flex flex-col justify-center">
          <div className="text-xl font-bold leading-none">
            <span className="text-slate-900 dark:text-white">Costing</span>
            <span className="text-purple-600 dark:text-purple-400">Hub</span>
          </div>
        </div>
      </div>

      <div className="bg-white dark:bg-slate-800 p-8 rounded-3xl shadow-xl w-full max-w-sm border border-gray-100 dark:border-slate-700 mt-12 md:mt-0">
        <div className="flex justify-center mb-6">
          <div className="bg-primary-600 p-4 rounded-2xl text-white shadow-lg shadow-primary-500/30">
            <ShieldCheck className="w-8 h-8" />
          </div>
        </div>
        
        <h2 className="text-2xl font-bold text-center text-slate-800 dark:text-white mb-2">Two-Factor Auth</h2>
        <p className="text-center text-slate-500 mb-8 text-sm">Enter the 6-digit verification code generated by your authenticator app.</p>

        <form onSubmit={handleVerify} className="space-y-6">
          <div>
            <input 
              type="text" 
              maxLength={6}
              autoFocus
              className="w-full text-center text-4xl font-black tracking-[0.5em] py-4 border-2 rounded-2xl dark:bg-slate-700 dark:border-slate-600 dark:text-white focus:border-primary-500 focus:ring-4 focus:ring-primary-500/10 transition-all outline-none"
              placeholder="000000"
              value={code}
              onChange={e => setCode(e.target.value.replace(/\D/g,''))}
            />
            {error && <div className="text-red-500 text-xs mt-3 text-center font-bold animate-in fade-in">{error}</div>}
          </div>

          <button 
            type="submit" 
            disabled={loading || code.length < 6}
            className="w-full bg-slate-900 dark:bg-primary-600 hover:bg-black dark:hover:bg-primary-700 text-white font-bold py-4 rounded-2xl shadow-xl transition-all active:scale-95 disabled:opacity-50 flex justify-center items-center gap-2"
          >
            {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : "Verify Identity"}
          </button>
        </form>

        <div className="mt-8 text-center">
            <button 
                onClick={() => navigate('/login')} 
                className="text-slate-400 hover:text-slate-600 text-xs font-bold uppercase tracking-widest"
            >
                Back to Sign In
            </button>
        </div>
      </div>
    </div>
  );
};
